### ISSUE TITLE
Domain name for LDMW

### ISSUE THREAD

**Issue by pm5k** [LDMW/app#116] opened 2017-05-09 09:48 UTC
@sarahwelton - following our discussion:

The - londonminds.co.uk domain was pointed to https://ldmw-app.herokuapp.com/, using a permanent redirect with masking, however since Heroku provides HTTPS with their own certificate (of some sort..) - the forwarding does not get masked and you can still see the heroku URL.

Perhaps it is easier if someone gives me whatever I need to shove into the dns records from heroku's side and I will make those point to the box? Or..?

**Comment by iteles** [comment] 2017-05-09 10:00
Duplicate of #10 :wink:

But @nelsonic has some good instructions on this. Will dig them up for you 👍

**Closed** 2017-05-09 10:02 UTC
