### ISSUE TITLE
Add emails from the alpha box input field to a shared Google spreadsheet

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#72] opened 2017-05-03 16:09 UTC
As a service provider, I want to gather email addresses of users who are interested in being involved with the alpha phase into a Google spreadsheet so that I can get in touch with them to give them more information, help them get involved and ask for valuable feedback

**Comment by Cleop** [comment] 2017-05-03 16:37
This is a duplicate of #59. Closing for this reason.

**Closed by Cleop** 2017-05-03 16:37 UTC
